name: image-gather
inputs:
  folder:
    required: true
  url:
    required: true
runs:
  using: "composite"
  steps:
      - name: Set file name
        id: filename
        shell: bash
        run: echo "::set-output name=filename::$(date +'%Y-%m-%d-%H-%M').jpg"
      - name: Retrieve file
        shell: bash
        run: |
          cd ${{ inputs.folder }}
          curl -o ${{ steps.filename.outputs.filename }} ${{ inputs.url }}
      - name: Validate file
        shell: bash
        id: validate
        run: |
          cd ${{ inputs.folder }}
          if ! [[ $(file -b '${{ steps.filename.outputs.filename }}') =~ JPEG ]]; then
            rm ${{ steps.filename.outputs.filename }};
            echo "::set-output name=is-removed::true"
          else
            echo "::set-output name=is-removed::false"
          fi
      - name: Remove duplication
        shell: bash
        if: (! steps.validate.outputs.is-removed) && hashFiles('$(cat inputs.folder/head-pointer)') == hashFiles('inputs.folder/steps.filename.outputs.filename')
        run: |
          cd ${{ inputs.folder }}
          if test -f '${{ steps.filename.outputs.filename }}'; then
            rm ${{ steps.filename.outputs.filename }};
          fi
      - name: Update pointer
        shell: bash
        run: |
          cd ${{ inputs.folder }}
          if test -f '${{ steps.filename.outputs.filename }}'; then
            echo ${{ steps.filename.outputs.filename }} > head-pointer;
          fi
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Automated commit by image-gather action'
