name: data-gather-periodic
run-name: Gather data periodically
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '10 * * * *'
    - cron:  '20 * * * *'
    - cron:  '30 * * * *'
    - cron:  '40 * * * *'
    - cron:  '50 * * * *'
jobs:
  data-gather-cityscape-1:
    name: Gather image for cityscape 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run image-gather action
        uses: ./.github/actions/image-gather
        with:
          folder: 'image-data/cityscape-1'
          url: 'http://nzmoray.co.nz/webcam/cam-image00001.jpg'
  data-gather-landscape-1:
    name: Gather image for seascape 1
    if: success() || failure()
    needs: data-gather-cityscape-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git pull
      - name: Run image-gather action
        uses: ./.github/actions/image-gather
        with:
          folder: 'image-data/seascape-1'
          url: 'https://www.wickednetworks.co.nz/webcams/current-stclair.jpg'
